export const INIT = 'INIT';
export const EVENT_GET_REQUEST = 'EVENT_GET_REQUEST';
export const EVENT_GET_SUCCESS = 'EVENT_GET_SUCCESS';
export const EVENT_GET_FAILURE = 'EVENT_GET_FAILURE';

export const CATEGORY_GET_REQUEST = 'CATEGORY_GET_REQUEST';
export const CATEGORY_GET_SUCCESS = 'CATEGORY_GET_SUCCESS';
export const CATEGORY_GET_FAILURE = 'CATEGORY_GET_FAILURE';

export const FORMAT_GET_REQUEST = 'FORMAT_GET_REQUEST';
export const FORMAT_GET_SUCCESS = 'FORMAT_GET_SUCCESS';
export const FORMAT_GET_FAILURE = 'FORMAT_GET_FAILURE';
